<a href="https://colab.research.google.com/github/NasTiaFox30/ColabProjects/blob/master/Decision_Trees_Hotel_Booking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**🌲🌳🏨 Decision Trees - Hotel Booking**

W oparciu o zbiór [Hotel Booking Cancellation Prediction](https://www.kaggle.com/datasets/youssefaboelwafa/hotel-booking-cancellation-prediction) przeprowadź proces predykcji wykorzystujący drzewa decyzyjne.

In [ ]:
import numpy as np
import gdown # pobieranie plików z usługi Google Drive
import pandas as pd # manipulacja i analiza danych
import matplotlib.pyplot as plt # wykresy i wizualizacja danych
from sklearn.model_selection import train_test_split # import funkcji train_test_split do podziału danych na zbiory treningowe i testowe
from sklearn.tree import DecisionTreeRegressor # model regresji oparty o drzewo
from sklearn.ensemble import RandomForestRegressor # model regresji oparty o lasy losowe
from sklearn.tree import plot_tree # funkcja z biblioteki sklearn.tree w Pythonie, która służy do wizualizacji drzewa decyzyjnego
from sklearn.metrics import r2_score # import funkcji r2_score,
                                     # która oblicza współczynnik determinancji
import seaborn as sns

In [ ]:
#
# kod
dataframe = pd.read_csv("booking.csv")
dataframe
#

,Booking_ID,number of adults,number of children,number of weekend nights,number of week nights,type of meal,car parking space,room type,lead time,market segment type,repeated,P-C,P-not-C,average price,special requests,date of reservation,booking status
0,INN00001,1,1,2,5,Meal Plan 1,0,Room_Type 1,224,Offline,0,0,0,88.00,0,10/2/2015,Not_Canceled
1,INN00002,1,0,1,3,Not Selected,0,Room_Type 1,5,Online,0,0,0,106.68,1,11/6/2018,Not_Canceled
2,INN00003,2,1,1,3,Meal Plan 1,0,Room_Type 1,1,Online,0,0,0,50.00,0,2/28/2018,Canceled
3,INN00004,1,0,0,2,Meal Plan 1,0,Room_Type 1,211,Online,0,0,0,100.00,1,5/20/2017,Canceled
4,INN00005,1,0,1,2,Not Selected,0,Room_Type 1,48,Online,0,0,0,77.00,0,4/11/2018,Canceled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36280,INN36282,2,0,0,2,Meal Plan 2,0,Room_Type 1,346,Online,0,0,0,115.00,1,9/13/2018,Canceled
36281,INN36283,2,0,1,3,Meal Plan 1,0,Room_Type 1,34,Online,0,0,0,107.55,1,10/15/2017,Not_Canceled
36282,INN36284,2,0,1,3,Meal Plan 1,0,Room_Type 4,83,Online,0,0,0,105.61,1,12/26/2018,Not_Canceled
36283,INN36285,3,0,0,4,Meal Plan 1,0,Room_Type 1,121,Offline,0,0,0,96.90,1,7/6/2018,Not_Canceled
36284,INN36286,2,0,0,5,Meal Plan 1,0,Room_Type 4,44,Online,0,0,0,133.44,3,10/18/2018,Not_Canceled

In [ ]:
X = dataframe.drop(columns=['Booking_ID', 'type of meal', 'room type', 'market segment type', 'date of reservation', 'booking status'], axis=1)
y = dataframe['lead time']

X_treningowe, X_testowe, y_treningowe, y_testowe = train_test_split(X, y, test_size=0.2, random_state=0)

drzewo2 = DecisionTreeRegressor(max_depth=5, random_state=0)
drzewo2.fit(X_treningowe, y_treningowe)

predykcja_drzewo2 = drzewo2.predict(X_testowe)

In [ ]:
# Obliczamy współczynnik determinacji R²
r2_drzewo = r2_score(y_testowe, predykcja_drzewo2)

print(f"Współczynnik determinacji R² dla drzewa decyzyjnego: {r2_drzewo}")

Współczynnik determinacji R² dla drzewa decyzyjnego: 0.9988652145349829